//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bono
    {
        public int Id { get; set; }
        public double vnominal { get; set; }
        public double vcomercial { get; set; }
        public int años { get; set; }
        public int frecuencia { get; set; }
        public int diasAño { get; set; }
        public string tipoInteres { get; set; }
        public Nullable<int> capitalizacion { get; set; }
        public double tasaInteres { get; set; }
        public double tasaDescuento { get; set; }
        public double impuestoRenta { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public double pPrima { get; set; }
        public double pEstructura { get; set; }
        public double pColoca { get; set; }
        public double pFlota { get; set; }
        public double pCAVALI { get; set; }
        public int UsuarioID { get; set; }
        public string nombre { get; set; }
        public string tipoActor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
